### PR TITLE
fix for issue #74

### PR DESCRIPTION
**Pull request by mammamao**
This fix prevents PRs with null authors to fail; it also reports the `name` field of such authors, so that identity can be validated.

### CODE REVIEW

**Comment by mammamao** [comment]
@ColinEberhardt - I'm working on this PR for issue #74, however test are still failing and I'm not 100% confident this is the right approach to take. Could you please have a look at the solution?

The important part of the solution is the `extractCommitterNames` const (in `cla-bot/index.js`), which basically returns the GitHub ID (preceded by an "@"), if available, otherwise it falls back into the authors name.

**Comment by maoo** [comment]
@ColinEberhardt - I'm working on this PR for issue #74, however test are still failing and I'm not 100% confident this is the right approach to take. Could you please have a look at the solution?

The important part of the solution is the extractCommitterNames const (in cla-bot/index.js), which basically returns the GitHub ID (preceded by an "@"), if available, otherwise it falls back into the authors name.

**Comment by maoo** [comment]
@ColinEberhardt , please close this PR, I created a new branch on my fork with a cleaner version, see https://github.com/ColinEberhardt/cla-bot/compare/develop...finos:fix-issue-74

**Comment by ColinEberhardt** [comment]
Thanks @maoo - I'll test this shortly. I've actually got a bunch of improvements that I haven't pushed yet, so I'll look to merge the two!

**Pull request closed without merging**
