### PR TITLE
A few incoming bug-fixes

### PR DESCRIPTION
**Pull request by ColinEberhardt**
There have been a few community-submitted bug-fixes that should be merged into the FINOS codebase...

https://github.com/ColinEberhardt/cla-bot/pull/9
https://github.com/ColinEberhardt/cla-bot/pull/10

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@rb-determined-ai).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by rb-determined-ai** [comment]
How does this work?  Do I need to sign a CLA then?

**Comment by maoo** [comment]
@rb-determined-ai - thanks for your contribution to FINOS!

To answer your question, yes, we ask our contributors to sign a CLA with FINOS before merging their first contributions, so that we can ensure IP compliance across all our hosted code.

We provide 2 types of CLAs, individual and corporate, you can read more on https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements

More than happy to provide you (and your employer, if necessary) with technical support and legal expertise.

Thank you!

**Comment by rb-determined-ai** [comment]
@maoo You should have received the email from my CTO at secretary@finos.org

**Comment by maoo** [comment]
> @maoo You should have received the email from my CTO at [secretary@finos.org](mailto:secretary@finos.org)

We did, thank you! Last thing I need is your full name and corporate email address; feel free to share them here or via help@finos.org (whatever is best for you). Thanks!

**Comment by rb-determined-ai** [comment]
@maoo responded to help@finos.org

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by mcleo-d** [comment]
@maoo and @ColinEberhardt 

PR #187 has been raised to fix the following issues that are breaking the Travis build.

James.

```
/home/travis/build/finos/cla-bot/src/contributionVerifier.js
  20:10  error  Replace `emailVerification,·usernameVerification]·=·partition(⏎····lowerCaseContributors,⏎····c·=>·c.includes("@")⏎··` with `⏎····emailVerification,⏎····usernameVerification⏎··]·=·partition(lowerCaseContributors,·c·=>·c.includes("@")`    prettier/prettier
  25:10  error  Replace `domainVerification,·exactEmailVerification]·=·partition(⏎····emailVerification,⏎····c·=>·c.startsWith("@")⏎··` with `⏎····domainVerification,⏎····exactEmailVerification⏎··]·=·partition(emailVerification,·c·=>·c.startsWith("@")`  prettier/prettier
✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by maoo** [comment]
So sorry to come late on this PR! I've reviewed it and LGTM. I'm merging into dev and run some tests on our staging environment. TY @rb-determined-ai and @ColinEberhardt !

**Pull request merged**
